- apiGroups:
    - ""
  resources:
    - events
  verbs:
    - create
    - patch
- apiGroups:
    - ""
  resources:
    - secrets
  verbs:
    - create
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - ""
  resources:
    - services
  verbs:
    - get
    - list
    - watch
- apiGroups:
    - coordination.k8s.io
  resources:
    - leases
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - core.openeverest.io
  resources:
    - instances
  verbs:
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - core.openeverest.io
  resources:
    - instances/finalizers
  verbs:
    - update
- apiGroups:
    - core.openeverest.io
  resources:
    - instances/status
  verbs:
    - get
    - patch
    - update
- apiGroups:
    - core.openeverest.io
  resources:
    - providers
  verbs:
    - get
    - list
    - watch
- apiGroups:
    - seaweed.seaweedfs.com
  resources:
    - seaweeds
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - seaweed.seaweedfs.com
  resources:
    - seaweeds/status
  verbs:
    - get
